name: Build and Test
on: [push]
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn

      - name: Check code style, lint and type-check code
        run: yarn check

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
