name: Build and Test
on: [push]
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install packages
        run: yarn

      - name: build
        run: yarn build

      - name: jest test
        run: yarn test
